import = ["/Users/maksymshutiak/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 5

[window]
decorations = "none"
dynamic_padding = false
opacity = 1.0
startup_mode = "Maximized"
